parameters:
    mapping:
        '[Product Code]': '[productCode]'
        '[Product Name]': '[productName]'
        '[Product Description]': '[productDesc]'
        '[Stock]': '[stock]'
        '[Cost in GBP]': '[cost]'
        '[Discontinued]': '[dateDiscontinued]'
       
